name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run -v $(pwd):/zap/wrk -t owasp/zap2docker-stable zap-baseline.py -t https://brave-meadow-0aff77e1e.6.azurestaticapps.net/ -r zap_report.html

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-security-report
          path: zap_report.html
